
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncpvqbqkguvgcsnjbhky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcHZxYnFrZ3V2Z2NzbmpiaGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjY5MjQsImV4cCI6MjA2MTg0MjkyNH0.sfDqZ_lG9_Yw8Tt36mt3eUo5z-huVrC11jdluf8ZODM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
